---
- name: git push 
  hosts: localhost
  become: yes

  vars:
    token: "{{ lookup('file', '/home/vagrant/WORK/git-token') }}"

  tasks:
    - name: print token 
      debug:
        msg: "{{ token }}"
      
    - name: git add 
      shell: git add .
      args:
        chdir: /home/vagrant/WORK/base_html_file

    - name: git commit 
      shell: |
        git config --global user.name "yeonkyu"
        git config --global user.email "yeonkyu@naver.com"
        git commit -m "commit with ansible"
      args:
        chdir: /home/vagrant/WORK/base_html_file

    - name: git push 
      shell: git push https://{{ token }}@github.com/yeonkyu-git/base_html_file.git
      args:
        chdir: /home/vagrant/WORK/base_html_file


- name: Deploy websource Nginx 
  hosts: nodes
  become: yes

  tasks:
    - name: delete html directory 
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: git pull 
      git: 
        repo: 'https://github.com/yeonkyu-git/base_html_file.git'
        dest: /usr/share/nginx/html
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted



        
        
