---
- name: git push 
  hosts: localhost
  become: yes

  vars:
    token: "{{ lookup('file', '/home/vagrant/WORK/git-token') }}"

  tasks:
    - name: git add & commit & push 
      shell: |
        git add /home/vagrant/WORK/base_html_file
        git commit -m "commit with ansible"
        git push https://{{ token }}@github.com/yeonkyu-git/base_html_file.git


- name: Deploy websource Nginx 
  hosts: nodes
  become: yes

  tasks:
    - name: delete html directory 
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: git pull 
      git: 
        repo: 'https://github.com/yeonkyu-git/base_html_file.git'
        dest: /usr/share/nginx/html
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted

